package tsql

import . "github.com/tbshill/goparsec"

var (
	ExpectBIGINTLiteral           = ExpectCaseInsensitiveString("BIGINT")
	ExpectBITLiteral              = ExpectCaseInsensitiveString("BIT")
	ExpectDECIMALLiteral          = ExpectCaseInsensitiveString("DECIMAL")
	ExpectINTLiteral              = ExpectCaseInsensitiveString("INT")
	ExpectMONEYLiteral            = ExpectCaseInsensitiveString("MONEY")
	ExpectNUMERICLiteral          = ExpectCaseInsensitiveString("NUMERIC")
	ExpectSMALLINTLiteral         = ExpectCaseInsensitiveString("SMALLINT")
	ExpectSMALLMONEYLiteral       = ExpectCaseInsensitiveString("SMALLMONEY")
	ExpectTINYINTLiteral          = ExpectCaseInsensitiveString("TINYINT")
	ExpectFLOATLiteral            = ExpectCaseInsensitiveString("FLOAT")
	ExpectREALLiteral             = ExpectCaseInsensitiveString("REAL")
	ExpectDATELiteral             = ExpectCaseInsensitiveString("DATE")
	ExpectDATETIME2Literal        = ExpectCaseInsensitiveString("DATETIME2")
	ExpectDATETIMELiteral         = ExpectCaseInsensitiveString("DATETIME")
	ExpectDATETIMEOFFSETLiteral   = ExpectCaseInsensitiveString("DATETIMEOFFSET")
	ExpectSMALLDATETIMELiteral    = ExpectCaseInsensitiveString("SMALLDATETIME")
	ExpectTIMELiteral             = ExpectCaseInsensitiveString("TIME")
	ExpectCHARLiteral             = ExpectCaseInsensitiveString("CHAR")
	ExpectVARCHARLiteral          = ExpectCaseInsensitiveString("VARCHAR")
	ExpectTEXTLiteral             = ExpectCaseInsensitiveString("TEXT")
	ExpectNCHARLiteral            = ExpectCaseInsensitiveString("NCHAR")
	ExpectNTEXTLiteral            = ExpectCaseInsensitiveString("NTEXT")
	ExpectNVARCHARLiteral         = ExpectCaseInsensitiveString("NVARCHAR")
	ExpectBINARYLiteral           = ExpectCaseInsensitiveString("BINARY")
	ExpectIMAGELiteral            = ExpectCaseInsensitiveString("IMAGE")
	ExpectVARBINARYLiteral        = ExpectCaseInsensitiveString("VARBINARY")
	ExpectROWVERSIONLiteral       = ExpectCaseInsensitiveString("ROWVERSION")
	ExpectHIERARCHYIDLiteral      = ExpectCaseInsensitiveString("HIERARCHYID")
	ExpectUNIQUEIDENTIFIERLiteral = ExpectCaseInsensitiveString("UNIQUEIDENTIFIER")
	ExpectSQL_VARIANTLiteral      = ExpectCaseInsensitiveString("SQL_VARIANT")
	ExpectXMLLiteral              = ExpectCaseInsensitiveString("XML")
)
